spring.application.name=client-app

# URL do Gateway — todas as requisições passam por aqui
gateway.url=http://localhost:8090

# Desabilita o servidor web (client-app só envia requisições, não recebe)
spring.main.web-application-type=none
